{{- if and .Values.serviceAccount.create .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kube-event-watcher.fullname" . }}
  labels:
    {{- include "kube-event-watcher.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kube-event-watcher.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kube-event-watcher.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
