apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kube-event-watcher.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-event-watcher.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: {{ .Values.prometheus.scrape | quote }}
    prometheus.io/port: {{ .Values.prometheus.port | quote }}
data:
  config.yaml: {{ .Values.configYaml | nindent 4 }}
