apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kube-event-watcher.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-event-watcher.labels" . | nindent 4 }}
type: Opaque
data:
  SLACK_CHANNEL: {{ .Values.slack.channel | b64enc | quote }}
  SLACK_TOKEN: {{ .Values.slack.token | b64enc | quote }}
