name: build

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
  AWS_REGION: "us-east-1"
  REGISTRY_ALIAS: "juny"
  REPOSITORY: "dev/kube-event-watcher"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🚀 [INIT] Clone repository
        uses: actions/checkout@v3

      - name: 🚀 [SET] Assume using OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: 🚀 [SET] Login to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: 'true'
          registry-type: public

      - name: 🚀 [SET] Get metadata
        id: meta
        env:
          REGISTRY: ${{ steps.ecr-login.outputs.registry }}
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.REGISTRY_ALIAS }}/${{ env.REPOSITORY }}

      - name: 🚀 [BUILD] Build and push image to ECR
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          provenance: false
          platforms: linux/amd64
